on:
  push:
    branches:
      - "develop"
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      # - name: install dependencies
      #   run: npm ci

      # - name: build
      #   run: npm run build

      - run: mkdir dist && cp main.py dist/main.py

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  release:
    runs-on: ubuntu-latest
    steps:
      - name: create release
        run: gh release create $REF_TAG -R $REPOSITORY -t $REF_TAG --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          REF_TAG: ${{ github.ref }} 
          REPOSITORY: ${{ github.repository }}

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: 
  #     - build
  #   steps:
  #     - name: download artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: dist
